### ISSUE TITLE
FastAPI compatibility with v15?

### ISSUE THREAD

**Issue by woh-dev** [OCA/rest-framework#372]
I'm very new Odoo but I'm looking into using the [FastApi framework offered here](https://github.com/OCA/rest-framework/tree/16.0/fastapi) to support an external frontend application. Is it only available for v16 or would this be compatible with Odoo v15 as well?

Is there an appropriate forum that I should use for noob questions like these, rather than opening an issue?

**Comment by woh-dev** [comment]
I just discovered that there are different branches in the repo for different Odoo versions. [The v15 branch](https://github.com/OCA/rest-framework/tree/15.0) does not include the FASTAPI offering. 

Am I correct to assume then that the FastApi integration is not available for v15?

**Comment by sbouillon** [comment]
If you’re planning on staying on v15 then it would probably make sense to use base_rest since it’s been widely used and has other modules that compliment it. 

I haven’t tested FastAPI v16 in v15 or looked deeply at the code but there was a lot of rework done by Odoo between v15 and 16 that could definitely make it unusable.
