### ISSUE TITLE
Not able to run the demo

### ISSUE THREAD

**Issue by omahboub** [OCA/rest-framework#81]
Hi,

Thank you for your contribution to this module. I have downloaded the base_rest with the base_rest_demo and add them to folders in odoo, but when calling from postman i get 500 internal error and when checking logs there is this 👍 
`odoo.addons.component.exception.NoComponentError: No component found for collection 'base.rest.demo.public.services', usage 'ping', model_name 'rest.service.registration'.`

from postman i used to call this url : http://localhost:8069/base_rest_demo_api/public/ping

**Comment by lmignon** [comment]
Hi

Are you sure all the addons are installed? If you have more than 1 database available for your Odoo you must also start you odoo with the dbfilter parameter to restrict the access to only one database otherwise when a call is done on a rest api endpoint, odoo is not able to know which database  must be used to serve the request.

**Comment by omahboub** [comment]
Yes, i copied base_rest and component in odoo/addons and the database is selected using config file at startup.
